"""Storage — TODO.

    class Repository(Protocol):
        def add(self, transaction: Transaction) -> None: ...
        def all(self) -> list[Transaction]: ...
        def totals_by_recipient(self) -> dict[tuple[str, Currency], Money]: ...

    class InMemoryRepository:   # NOT a subclass of Repository - structural typing
        ...

`all()` must return a copy, so callers cannot mutate the internal list.
"""
